In [10]:
import numpy as np

对于ndarray结构来说，里面所有的元素必须是同一类型的
如果不是的话，会自动的向下进行转换

In [11]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
#list swich to ndarray
tang_array

array([1, 2, 3, 4, 5])

ndarray基本属性操作

In [12]:
type(tang_array)

numpy.ndarray

In [13]:
tang_array.dtype

dtype('int64')

dtype看array数组元素类型，向下兼容

In [14]:
tang_array.itemsize

8

itemsize看元素字节数大小

In [15]:
tang_array.shape #看维度

(5,)

shape看维度以及每维度大小

In [16]:
tang_array.size

5

size不看维度，只看大小 = 长x宽x高

In [17]:
np.size(tang_array)

5

.size 的替换方法，没必要使用

In [18]:
np.shape(tang_array)

(5,)

In [19]:
tang_array.ndim # 维度

1

.ndim只看维度大小

In [20]:
tang_array

array([1, 2, 3, 4, 5])

In [21]:
tang_array.fill(0) # 填充之后全部赋值
tang_array

array([0, 0, 0, 0, 0])

数值填充替换

索引与切片:跟Python都是一样的 还是从0开始的

In [22]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array[0]

np.int64(1)

np.array(list) 将list直接转换为ndarray

In [23]:
tang_array[1:3]

array([2, 3])

切片规则与python的list类似

In [24]:
tang_array[-2:]

array([4, 5])

矩阵格式（多维的形式）

In [25]:
tang_array = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
tang_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
tang_array.shape

(3, 3)

In [27]:
tang_array.size

9

In [28]:
tang_array.ndim

2

In [29]:
tang_array[1,1]

np.int64(5)

In [30]:
tang_array[1,1] = 10
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [31]:
tang_array[1]

array([ 4, 10,  6])

In [32]:
tang_array[:,1] # ： 意味着行全取

array([ 2, 10,  8])

In [33]:
tang_array[0,0:2]

array([1, 2])

In [34]:
tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [35]:
tang_array2 = tang_array # 浅拷贝
tang_array2

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [36]:
tang_array2[1,1] = 100
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [37]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [38]:
tang_array2 = tang_array.copy()
tang_array2

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

依然需要.copy进行深拷贝

In [39]:
tang_array2[1,1] = 10000
tang_array2

array([[    1,     2,     3],
       [    4, 10000,     6],
       [    7,     8,     9]])

In [40]:
tang_array

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [41]:
tang_array = np.arange(0,100,10)
# 0 -100之间每10构造一个
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

arrange按规则构造等差数列

In [42]:
mask = np.array([9,0,0,1,7,8,0,0,1,1],dtype=bool)
#这里只有0，1也要指定bool类型，默认会存储为int64
mask

array([ True, False, False,  True,  True,  True, False, False,  True,
        True])

mask使用dtype = bool强制转换bool类型作为筛选条件

In [43]:
tang_array[mask] #相当于筛选条件了，只有当mask对应位置为true的才保留在array中

array([ 0, 30, 40, 50, 80, 90])

使用数组嵌套数组的方法直接筛选

In [44]:
random_array = np.random.rand(10)
random_array

array([0.19910259, 0.96610636, 0.60565429, 0.34604605, 0.32297109,
       0.71797646, 0.15635227, 0.01644507, 0.94362545, 0.594521  ])

In [45]:
mask = random_array > 0.5 #直接利用表达式作为筛选条件
mask

array([False,  True,  True, False, False,  True, False, False,  True,
        True])

In [46]:
tang_array[mask]

array([10, 20, 50, 80, 90])

In [47]:
tang_array = np.array([10,20,30,40,50])
tang_array > 30

array([False, False, False,  True,  True])

In [48]:
np.where(tang_array > 30) #看看大于30的在什么位置

(array([3, 4]),)

 where查找满足条件（true）的位置

In [49]:
tang_array[np.where(tang_array > 30)]

array([40, 50])

In [50]:
tang_array[tang_array > 30]

array([40, 50])

In [51]:
tang_array = np.array([1,2,3,4,5],dtype=np.float32)
tang_array

array([1., 2., 3., 4., 5.], dtype=float32)

指定列表类型


In [52]:
tang_array.nbytes

20

In [53]:
tang_array.itemsize

4

4x5一共占用40字节 bytes查找总共占用空间

In [54]:
tang_array = np.array([1,10,3.5,'str'],dtype = object)
tang_array

array([1, 10, 3.5, 'str'], dtype=object)

In [55]:
tang_array * 2

array([2, 20, 7.0, 'strstr'], dtype=object)

In [56]:
tang_array = np.array([1,2,3,4,5])
np.asarray(tang_array,dtype = np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

利用np.asarray转换类型，但是原始的列表无法改变

In [57]:
tang_array

array([1, 2, 3, 4, 5])

需要赋值

In [58]:
tang_array2 = np.asarray(tang_array,dtype = np.float32)

In [59]:
tang_array2

array([1., 2., 3., 4., 5.], dtype=float32)

In [60]:
tang_array

array([1, 2, 3, 4, 5])

In [61]:
tang_array.astype(np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

astype也无法修改原列表

In [62]:
tang_array

array([1, 2, 3, 4, 5])