 ### array数组的数值计算

In [1]:
import numpy as np
tang_array = np.array([[1,2,3],[4,5,6]])
tang_array

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.sum(tang_array)

np.int64(21)

指定要进行的操作是沿着什么轴（维度）

In [5]:
np.sum(tang_array,axis=0)

array([5, 7, 9])

In [6]:
tang_array.ndim

2

In [7]:
np.sum(tang_array,axis=1)

array([ 6, 15])

In [8]:
np.sum(tang_array,axis=-1)

array([ 6, 15])

高纬度数组想要沿着最后一个轴求和，可以用axis = -1

In [9]:
tang_array.sum()

np.int64(21)

In [12]:
tang_array

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
tang_array.sum(axis = 0)

array([5, 7, 9])

In [14]:
tang_array.sum(axis = 1)

array([ 6, 15])

In [15]:
tang_array.prod()

np.int64(720)

prod计算数组中所有元素求积

In [16]:
tang_array.prod(axis = 0)

array([ 4, 10, 18])

In [17]:
tang_array.prod(axis = 1)

array([  6, 120])

指定轴乘积


In [18]:
tang_array.min()

np.int64(1)

In [19]:
tang_array.min(axis = 0)

array([1, 2, 3])

In [20]:
tang_array.min(axis = 1)

array([1, 4])

横纵求最小值

In [17]:
tang_array.max()

6

求最大值

找到索引位置

In [22]:
tang_array.argmin()

np.int64(0)

找最小值在什么位置（索引）

In [23]:
tang_array.argmin(axis = 0)

array([0, 0, 0])

In [24]:
tang_array.argmin(axis=1)

array([0, 0])

In [25]:
tang_array.argmax()

np.int64(5)

In [26]:
tang_array.mean()

np.float64(3.5)

均值

In [27]:
tang_array.mean(axis = 0)

array([2.5, 3.5, 4.5])

###标准差

In [28]:
tang_array.std()

1.707825127659933

求标准差

In [28]:
tang_array.std(axis = 1)

array([0.81649658, 0.81649658])

###方差的计算

In [30]:
tang_array.var()

np.float64(2.9166666666666665)

求方差

In [31]:
tang_array

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
tang_array.clip(2,4)

array([[2, 2, 3],
       [4, 4, 4]])

对数组进行限制，小于2的值都变成2，大于4的值都变成4

In [33]:
tang_array = np.array([1.2,3.56,6.41])

In [34]:
tang_array.round()

array([1., 4., 6.])

四舍五入

In [35]:
tang_array.round(decimals=1)

array([1.2, 3.6, 6.4])

指定四舍五入精度