In [2]:
import numpy as np
tang_array = np.array([[1.5,1.3,7.5],
                      [5.6,7.8,1.2]])
tang_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [3]:
np.sort(tang_array)

array([[1.3, 1.5, 7.5],
       [1.2, 5.6, 7.8]])

In [4]:
np.sort(tang_array,axis = 0)

array([[1.5, 1.3, 1.2],
       [5.6, 7.8, 7.5]])

按列排序

In [5]:
tang_array

array([[1.5, 1.3, 7.5],
       [5.6, 7.8, 1.2]])

In [6]:
np.argsort(tang_array)

array([[1, 0, 2],
       [2, 0, 1]])

对行排序，但是返回索引值

In [7]:
tang_array = np.linspace(0,10,10)
tang_array

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

在 0 到 10 之间（包含 0 和 10），均匀地切分出 10 个数字
和np.arrange的区别是
linspace是全闭区间，而arrage是左闭右开区间

In [8]:
values = np.array([2.5,6.5,9.5])

In [9]:
np.searchsorted(tang_array,values)

array([3, 6, 9])

values想要插入tange_array，应该插入什么位置（索引）
注意tang_array应当是排序好的数组，才能使用searchsorted

In [12]:
tang_array = np.array([[1,0,6],
                       [1,7,0],
                       [2,3,1],
                       [2,4,0]])
tang_array

array([[1, 0, 6],
       [1, 7, 0],
       [2, 3, 1],
       [2, 4, 0]])

In [13]:
index = np.lexsort([-1*tang_array[:,0],tang_array[:,2]])
index

array([3, 1, 2, 0])

分开指定排序
-1*（倒序）tang_array[:,0]（倒叙排列）

In [16]:
tang_array = tang_array[index]
tang_array

array([[2, 4, 0],
       [1, 7, 0],
       [2, 3, 1],
       [1, 0, 6]])

使用索引排序
第三列升序（后排序但结果优先级更高），然后第一列降序（先排序）