### 数组形状操作

In [1]:
import numpy as np
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
tang_array.shape

(10,)

In [6]:
tang_array.shape = 2,5

将array的维度改为2维，2行5列

In [16]:
tang_array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
tang_array.shape = 1,10
tang_array

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
tang_array.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

大小必须不能改变,数组n*m一定要等于元素个数

In [12]:
tang_array .shape = 3,4

ValueError: cannot reshape array of size 10 into shape (3,4)

In [19]:
tang_array = np.arange(10)
tang_array.shape

(10,)

In [25]:
tang_array = tang_array[np.newaxis,:]
tang_array.shape

(1, 1, 1, 1, 1, 10)

In [27]:
tang_array = tang_array[:,np.newaxis,np.newaxis]
tang_array.shape

(1, 1, 1, 1, 1, 1, 1, 10)

可以随意增加维度

In [29]:
tang_array = np.arange(10)
tang_array.shape

(10,)

In [30]:
tang_array = tang_array[:,np.newaxis]
tang_array.shape

(10, 1)

In [31]:
tang_array = tang_array[:,np.newaxis,np.newaxis]
tang_array.shape

(10, 1, 1, 1)

In [32]:
tang_array = tang_array.squeeze()
tang_array.shape

(10,)

将空轴压缩去除

In [33]:
tang_array.shape = 2,5

In [34]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
tang_array.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

转置，将2行5列转置为5行2列

In [36]:
tang_array.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

transpose和.T转置效果相同，都不改变原数组，需要重新赋值

In [37]:
tang_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 数组的连接

In [38]:
a = np.array([[123,456,678],[3214,456,134]])
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [39]:
b = np.array([[1235,3124,432],[43,13,134]])
b

array([[1235, 3124,  432],
       [  43,   13,  134]])

a，b都是两行三列的

In [40]:
c = np.concatenate((a,b))
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

concatenate进行连接操作，括号内需要将a，b
写成类似元组的形式（a，b）
默认按照第一个维度拼接（行拼接）

In [41]:
c = np.concatenate((a,b),axis = 0)
c

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [42]:
c = np.concatenate((a,b),axis = 1)
c

array([[ 123,  456,  678, 1235, 3124,  432],
       [3214,  456,  134,   43,   13,  134]])

按照第二个维度拼接

In [43]:
c.shape

(2, 6)

In [44]:
np.vstack((a,b))

array([[ 123,  456,  678],
       [3214,  456,  134],
       [1235, 3124,  432],
       [  43,   13,  134]])

In [ ]:
np.hstack((a,b))

vstack和hstack分别类似于行拼接、列拼接

In [46]:
a

array([[ 123,  456,  678],
       [3214,  456,  134]])

In [51]:
a.flatten()

array([ 123,  456,  678, 3214,  456,  134])

flatten按行拉平

In [48]:
a


array([[ 123,  456,  678],
       [3214,  456,  134]])

In [55]:
a.ravel()

array([ 123,  456,  678, 3214,  456,  134])

ravel也可以按行拉平