### 数组生成

In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

构造出来一个数组

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

arrange左闭右开区间

In [4]:
np.arange(2,20,2,dtype=np.float32)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=float32)

arrage指定type和类型精度

In [5]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

linspace双闭区间，构造n个数的等差数列，自动进行计算

不知道怎么用可以看帮助文档

In [12]:
print(help(np.logspace(10,20)))

Help on ndarray:

array([1.00000000e+10, 1.59985872e+10, 2.5595479...3994e+19,
       6.25055193e+19, 1.00000000e+20])
    ndarray(shape, dtype=None, buffer=None, offset=0, strides=None, order=None)
    --

    ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)

    An array object represents a multidimensional, homogeneous array
    of fixed-size items.  An associated data-type object describes the
    format of each element in the array (its byte-order, how many bytes it
    occupies in memory, whether it is an integer, a floating point number,
    or something else, etc.)

    Arrays should be constructed using `array`, `zeros` or `empty` (refer
    to the See Also section below).  The parameters given here refer to
    a low-level method (`ndarray(...)`) for instantiating an array.

    For more information, refer to the `numpy` module and examine the
    methods and attributes of an array.

    Parameters
    ----------
    (for the __new__ method; see No

logspace默认是10为底的

In [19]:
np.logspace(0,1,5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

第一个参数 0 (start)：这是指数的起始值。
代表从 $10^0$（即 1）开始。
第二个参数 1 (stop)：这是指数的结束值。
代表到 $10^1$（即 10）结束。
第三个参数 5 (num)：在这两个边界之间，一共生成 5 个数字。

第一步：系统先偷偷用 np.linspace(0, 1, 5) 生成 5 个均匀的指数：[0, 0.25, 0.5, 0.75, 1]。

第二步：把底数 10 的这些次方算出来：[$10^0$, $10^{0.25}$, $10^{0.5}$, $10^{0.75}$, $10^1$]。

In [14]:
x = np.linspace(-10,10,5)
x

array([-10.,  -5.,   0.,   5.,  10.])

In [15]:
y = np.linspace(-10,10,5)
y

array([-10.,  -5.,   0.,   5.,  10.])

In [16]:
x, y= np.meshgrid(x,y)

构造二维网格

In [20]:
x

array([[-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.],
       [-10.,  -5.,   0.,   5.,  10.]])

In [21]:
y

array([[-10., -10., -10., -10., -10.],
       [ -5.,  -5.,  -5.,  -5.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  5.,   5.,   5.,   5.,   5.],
       [ 10.,  10.,  10.,  10.,  10.]])

x横着的，y数着的

In [23]:
np.r_[0:10:1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.c_[0:10:1]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

r/c控制分别构造行向量和列向量

### 更常用的 zeros ones

In [25]:
np.zeros(3)

array([0., 0., 0.])

构造全是0的数组

In [26]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

构造出很多个值为1的矩阵

In [29]:
np.ones((3,3)) * 3.2

array([[3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2],
       [3.2, 3.2, 3.2]])

In [30]:
np.ones((3,3),dtype = np.float32)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [31]:
a = np.empty(6)
a.shape

(6,)

In [32]:
a

array([ 1.79769313e+308, -1.79769313e+308,  2.00000000e+000,
        2.22044605e-016,  2.22507386e-308,  4.94065646e-324])

构造出来的空数组，数组被随机赋值

In [33]:
a.fill(1)
a

array([1., 1., 1., 1., 1., 1.])

向数组中填充元素

In [34]:
tang_array = np.array([1,2,3,4])
tang_array

array([1, 2, 3, 4])

In [43]:
np.zeros_like(tang_array)

array([0, 0, 0, 0])

In [35]:
np.ones_like(tang_array) * 5

array([5, 5, 5, 5])

构造与对象数组维度一致的全0/1数组

In [45]:
np.identity(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])