### 矩阵运算

In [1]:
import numpy as np

In [6]:
x = np.array([5,5])
y = np.array([2,2])

In [4]:
x = np.array([5,5])
y = np.array([2,4])

In [7]:
np.multiply(x,y)

array([10, 10])

数组对应位置分别做乘法


In [8]:
np.dot(x,y)

np.int64(20)

矩阵相乘

In [9]:
x.shape

(2,)

In [10]:
y.shape

(2,)

In [11]:
x.shape = 2,1

In [12]:
x

array([[5],
       [5]])

In [13]:
np.dot(x,y)

ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

只有维度一样才能进行计算（m x n与n x p）

In [16]:
y.shape = 1,2
y

array([[2, 2]])

In [17]:
x

array([[5],
       [5]])

In [18]:
print (x.shape)
print (y.shape)

(2, 1)
(1, 2)


In [19]:
np.dot(x,y)

array([[10, 10],
       [10, 10]])

In [20]:
np.dot(y,x)

array([[20]])

In [27]:
x = np.array([1,1,1])
y = np.array([[1,2,3],[4,5,6]])
print (x * y)

[[1 2 3]
 [4 5 6]]


In [25]:
z = y.T
z

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
np.dot(x,z)

array([ 6, 15])

In [28]:
y = np.array([1,1,1,4])
x = np.array([1,1,1,2])
x == y

array([ True,  True,  True, False])

对应每个位置进行判断


In [29]:
np.logical_and(x,y)

array([ True,  True,  True,  True])

与操作，两个都是True（！= 0）即返回True

In [30]:
np.logical_or(x,y)

array([ True,  True,  True,  True])

In [31]:
np.logical_not(x,y)

array([0, 0, 0, 0])

与或非