### Numpy的随机模块

In [3]:
import numpy as np
#所有的值都是从0到1
np.random.rand(3,2)

array([[0.61117522, 0.4260138 ],
       [0.4116863 , 0.55580594],
       [0.86895368, 0.97061114]])

构造一个三行两列的随机0-1浮点数

In [8]:
#返回的是随机的整数，左闭右开
np.random.randint(10,size = (5,4))

array([[7, 7, 9, 3],
       [3, 8, 1, 5],
       [5, 1, 8, 0],
       [9, 9, 6, 5],
       [8, 4, 6, 9]])

随机整数，左闭右开

In [11]:
np.random.rand()

0.8345954896782098

返回一个数而非矩阵

In [12]:
np.random.random_sample()

0.40958693120100165

In [13]:
np.random.randint(0,10,3)

array([4, 7, 5])

0-10之间取3个整数

In [15]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([-0.11763042,  0.09376664,  0.16592195,  0.11370185,  0.07351664,
       -0.16033358, -0.08178878, -0.06806565,  0.10491532,  0.00056513])

高斯分布

In [24]:
np.set_printoptions(precision = 4)

在numpy中设置打印精度

In [25]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([-0.1115,  0.0673,  0.0209,  0.1234, -0.0187, -0.0109, -0.0248,
        0.0726,  0.0383,  0.0269])

### 洗牌

In [26]:
tang_array = np.arange(10)
tang_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.random.shuffle(tang_array)

shuffle给数据打乱顺序

In [28]:
tang_array

array([8, 1, 2, 3, 7, 0, 9, 6, 4, 5])

### 随机的种子

In [38]:
np.random.seed(101)

In [39]:
mu, sigma = 0,0.1
np.random.normal(mu,sigma,10)

array([ 0.2707,  0.0628,  0.0908,  0.0504,  0.0651, -0.0319, -0.0848,
        0.0606, -0.2018,  0.074 ])

设定种子之后剩下所有随机都是依据种子来做的，当对比实验的时候，保证随机是“伪随机”，对比相同