In [2]:
import numpy as np

In [3]:
print(np.__version__)

2.4.2


In [6]:
z = np.zeros((5,5))
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
print(z.nbytes)
print('%d bytes'%(z.size*z.itemsize))

200
200 bytes


In [10]:
print(help(np.add))

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [20]:
tang_array = np.arange(10,50,1)
tang_array = tang_array[::-1] # 这是 Python 的切片语法，意思是“从头到尾，步长为 -1（即反向取值）”。

In [29]:
np.where(tang_array != 0)
np.nonzero([1,2,3,4,5,0,0,0,1234,0,1])

(array([ 0,  1,  2,  3,  4,  8, 10]),)

In [33]:
tang_array = np.random.randint(0,10,(3,3))
tang_array

array([[3, 0, 3],
       [7, 2, 0],
       [8, 2, 9]])

In [34]:
tang_array.max()

np.int64(9)

In [36]:
tang_array.min()

np.int64(0)

In [41]:
tang_array = np.ones((5,5))
tang_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
tang_array = np.pad(tang_array,pad_width = 1,mode = 'constant',constant_values = 0)
tang_array

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

我们来拆解这四个关键参数：

tang_array：你要处理的原数组。

pad_width = 2：填充的厚度。

意思是：在数组的上下左右（如果是二维）或者前后（如果是一维）各增加 2 层数据。

mode = 'constant'：填充模式。

constant 代表“常量填充”，也就是用一个固定的数字去填满新增加的那 2 层空间。

constant_values = 0：填充的具体数值。

既然选择了常量模式，这里就指定用 0 来填充。

In [43]:
np.unravel_index(100,(6,7,8)) # 先遍历最后一维→列，再中间→行，最后第一维→块

(np.int64(1), np.int64(5), np.int64(4))

块号         行号             列号

### 归一化处理


In [45]:
tang_array = np.random.random((5,5))
tang_array

array([[0.39747359, 0.51533975, 0.2257605 , 0.97222971, 0.65939152],
       [0.04888128, 0.97609595, 0.40010425, 0.47374035, 0.63266034],
       [0.66876386, 0.06279242, 0.8461768 , 0.47624881, 0.05614961],
       [0.59527682, 0.76761015, 0.00649717, 0.07442897, 0.11387812],
       [0.32527949, 0.49871581, 0.73878877, 0.25237639, 0.14505285]])

In [47]:
tang_max = tang_array.max()
tang_min = tang_array.min()
tang_array = (tang_array-tang_min)/(tang_max - tang_min)
tang_array

array([[0.40323526, 0.52479705, 0.22613821, 0.99601253, 0.67336548],
       [0.04371304, 1.        , 0.40594841, 0.48189333, 0.64579616],
       [0.68303168, 0.05806035, 0.86600731, 0.48448044, 0.05120927],
       [0.60724051, 0.78497725, 0.        , 0.07006177, 0.11074782],
       [0.32877756, 0.50765188, 0.75525219, 0.25358862, 0.14290002]])

In [57]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print (z1)
print (z2)
print (np.intersect1d(z1,z2))
#求两个数组的交集（即同时出现在 z1 和 z2 中的元素），且返回结果会自动去重 + 升序排序。

[2 0 8 2 0 0 5 2 5 8]
[5 7 3 4 1 9 8 7 7 6]
[5 8]


In [58]:
# 找出z1中属于交集的元素的索引
intersect_vals = np.intersect1d(z1,z2)
indices = np.where(np.isin(z1, intersect_vals))[0]
print("z1中交集元素的索引：", indices)

z1中交集元素的索引： [2 6 8 9]


In [59]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
today = np.datetime64('today','D')
tommorow = np.datetime64('today','D') + np.timedelta64(1,'D')

In [60]:
yesterday

np.datetime64('2026-03-07')

In [61]:
today

np.datetime64('2026-03-08')

In [62]:
tommorow

np.datetime64('2026-03-09')

In [66]:
np.arange('2017-10','2017-11',dtype = 'datetime64[30m]')

array(['2017-10-01T00:00', '2017-10-01T00:30', '2017-10-01T01:00', ...,
       '2017-10-31T22:30', '2017-10-31T23:00', '2017-10-31T23:30'],
      shape=(1488,), dtype='datetime64[30m]')

In [68]:
z = np.random.uniform(0,10,10)
np.floor(z)

array([6., 8., 4., 8., 6., 2., 6., 3., 4., 0.])

In [69]:
z = np.zeros(5)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

In [72]:
np.set_printoptions(threshold = 5)
#threshold=5：表示当数组的总元素数超过 5 个时，NumPy 不会打印所有元素，而是只显示 “开头 + 结尾” 的部分，中间用...省略（避免输出过长）；
z = np.zeros((15,15))
z

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(15, 15))

In [73]:
np.set_printoptions(threshold = np.inf) #恢复默认规则

In [77]:
z = np.arange(100)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(z-v)).argmin()
print(z[index])

42.82042148545674
43


In [80]:
z = np.arange(10,dtype=np.int32)
print (z.dtype)
z = z.astype(np.float32)
print(type(z.dtype))

int32
<class 'numpy.dtypes.Float32DType'>


In [81]:
z = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(z):
    print (index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
